-- AlterTable
ALTER TABLE `vendor` ADD COLUMN `address` VARCHAR(191) NULL,
    ADD COLUMN `coverImage` VARCHAR(191) NULL,
    ADD COLUMN `image` VARCHAR(191) NULL,
    ADD COLUMN `logo` VARCHAR(191) NULL,
    ADD COLUMN `tinCertificate` VARCHAR(191) NULL,
    ADD COLUMN `tinExpireDate` DATETIME(3) NULL,
    ADD COLUMN `tinNumber` VARCHAR(191) NULL;
