-- AlterTable
ALTER TABLE `order` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'PACKAGING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELED', 'RETURNED', 'FAILED_TO_DELIVER') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `suborder` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'PACKAGING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELED', 'RETURNED', 'FAILED_TO_DELIVER') NOT NULL DEFAULT 'PENDING';
